#!/bin/sh

#
# Configuration
#

# Read code limit parameter
codelimit=2048
if [ $# -gt 1 ]; then
	codelimit="$2"
fi

# Reade data limit parameter
datalimit=96    # leave 32 bytes for stack
if [ $# -gt 2 ]; then
	datalimit="$3"
fi


#
# Main
#

error=0

# Check code size
set -- `avr-size -d "$1" | awk '/[0-9]/ {print $1 + $2, $2 + $3, $2}'`
if [ $1 -gt $codelimit ]; then
	echo "*** Code size $1 exceeds limit of $codelimit"
	error=1
else
	echo "Flash: $1 bytes (data=$3)"
fi

# Check data size
if [ $2 -gt $datalimit ]; then
	echo "*** Data size $2 exceeds limit of $datalimit"
	error=1
else
	echo "RAM:   $2 bytes"
fi

exit $error

